# Generated by Django 6.0.1 on 2026-05-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药品名称')),
                ('pinyin_code', models.CharField(db_index=True, max_length=50, verbose_name='拼音首字母')),
                ('specification', models.CharField(max_length=100, verbose_name='规格')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='生产厂家')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('warning_stock', models.PositiveIntegerField(default=10, verbose_name='预警库存')),
                ('expiry_date', models.DateField(verbose_name='有效期至')),
                ('category', models.CharField(choices=[('western', '西药'), ('chinese_patent', '中成药'), ('external', '外用药'), ('injection', '注射剂'), ('other', '其他')], max_length=50, verbose_name='药品分类')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
                'db_table': 'medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.PositiveIntegerField(verbose_name='系统库存')),
                ('actual_quantity', models.PositiveIntegerField(verbose_name='实际库存')),
                ('difference', models.IntegerField(verbose_name='差异数量')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='盘点时间')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_checks', to='pharmacy.medicine', verbose_name='药品')),
                ('operator', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'pharmacist']}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_checks', to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'db_table': 'stock_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='入库数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='入库单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='总金额')),
                ('batch_number', models.CharField(max_length=50, verbose_name='批号')),
                ('supplier', models.CharField(blank=True, default='', max_length=100, verbose_name='供应商')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to='pharmacy.medicine', verbose_name='药品')),
                ('operator', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'pharmacist']}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ins', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '药品入库',
                'verbose_name_plural': '药品入库',
                'db_table': 'stock_ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='出库数量')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to='pharmacy.medicine', verbose_name='药品')),
                ('operator', models.ForeignKey(limit_choices_to={'role__in': ['admin', 'pharmacist']}, on_delete=django.db.models.deletion.PROTECT, related_name='stock_outs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_outs', to='medical.prescription', verbose_name='关联处方')),
            ],
            options={
                'verbose_name': '药品出库',
                'verbose_name_plural': '药品出库',
                'db_table': 'stock_outs',
                'ordering': ['-created_at'],
            },
        ),
    ]
