# Generated by Django 6.0.1 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科室名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='科室描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科室',
                'verbose_name_plural': '科室',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
    ]
