# Generated by Django 6.0.1 on 2026-05-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('dosage', models.CharField(max_length=100, verbose_name='用法用量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
            ],
            options={
                'verbose_name': '处方明细',
                'verbose_name_plural': '处方明细',
                'db_table': 'prescription_items',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(verbose_name='主诉')),
                ('present_illness', models.TextField(blank=True, default='', verbose_name='现病史')),
                ('past_history', models.TextField(blank=True, default='', verbose_name='既往史')),
                ('physical_examination', models.TextField(blank=True, default='', verbose_name='体格检查')),
                ('diagnosis', models.TextField(verbose_name='诊断结果')),
                ('treatment_plan', models.TextField(blank=True, default='', verbose_name='治疗方案')),
                ('advice', models.TextField(blank=True, default='', verbose_name='医嘱建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='appointments.appointment', verbose_name='关联挂号')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '电子病历',
                'verbose_name_plural': '电子病历',
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NursingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('blood_pressure', models.CharField(blank=True, default='', max_length=20, verbose_name='血压(mmHg)')),
                ('heart_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='心率(次/分)')),
                ('medical_order', models.TextField(verbose_name='医嘱内容')),
                ('execution_status', models.CharField(choices=[('pending', '待执行'), ('executed', '已执行'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='护理备注')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_records', to='appointments.appointment', verbose_name='关联挂号')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.PROTECT, related_name='nursing_records', to=settings.AUTH_USER_MODEL, verbose_name='执行护士')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nursing_records', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '护理记录',
                'verbose_name_plural': '护理记录',
                'db_table': 'nursing_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('pending', '待缴费'), ('paid', '已缴费'), ('dispensed', '已发药'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='处方状态')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('dispense_time', models.DateTimeField(blank=True, null=True, verbose_name='发药时间')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开方时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='appointments.appointment', verbose_name='关联挂号')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='开方医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient', verbose_name='患者')),
                ('pharmacist', models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='发药药剂师')),
            ],
            options={
                'verbose_name': '处方',
                'verbose_name_plural': '处方',
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
