# Generated by Django 6.0.1 on 2026-05-14 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='就诊日期')),
                ('appointment_time', models.TimeField(verbose_name='就诊时段')),
                ('status', models.CharField(choices=[('pending', '待就诊'), ('completed', '已就诊'), ('cancelled', '已取消'), ('expired', '已过期')], default='pending', max_length=20, verbose_name='挂号状态')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='挂号费')),
                ('payment_status', models.BooleanField(default=False, verbose_name='支付状态')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝')], default='', max_length=20, verbose_name='支付方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='挂号时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='departments.department', verbose_name='科室')),
                ('doctor', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '挂号',
                'verbose_name_plural': '挂号',
                'db_table': 'appointments',
                'ordering': ['-appointment_date', '-appointment_time'],
                'indexes': [models.Index(fields=['appointment_date', 'status'], name='appointment_appoint_b9472b_idx'), models.Index(fields=['doctor', 'appointment_date'], name='appointment_doctor__4449b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='排班日期')),
                ('max_patients', models.PositiveIntegerField(default=30, verbose_name='最大号源数')),
                ('current_patients', models.PositiveIntegerField(default=0, verbose_name='已挂号数')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可挂号')),
                ('doctor', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='医生')),
            ],
            options={
                'verbose_name': '医生排班',
                'verbose_name_plural': '医生排班',
                'db_table': 'doctor_schedules',
                'ordering': ['date'],
                'unique_together': {('doctor', 'date')},
            },
        ),
    ]
