# Generated by Django 6.0.1 on 2026-05-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=10, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('allergy_history', models.TextField(blank=True, default='', verbose_name='过敏史')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建档时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
